---
swagger: "2.0"
info:
  description: "This is an online swagger codegen server.  You can find out more at\n\
    https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: "2.1.7"
  title: "Swagger Generator"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "internal-virtserver.swaggerhub.com"
basePath: "/virts/bgriffin/generator-api/2.1.7"
tags:
- name: "gen"
- name: "clients"
- name: "servers"
schemes:
- "https"
paths:
  /gen/clients:
    get:
      tags:
      - "clients"
      summary: "Gets languages supported by the client generator"
      operationId: "clientOptions"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
  /gen/clients/{language}:
    get:
      tags:
      - "clients"
      summary: "Returns options for a client library"
      operationId: "getClientOptions"
      produces:
      - "application/json"
      parameters:
      - name: "language"
        in: "path"
        description: "The target language for the client library"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              $ref: "#/definitions/CliOption"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
    post:
      tags:
      - "clients"
      summary: "Generates and downloads a client library"
      description: "Accepts a `GeneratorInput` options map for spec location and generation\
        \ options"
      operationId: "generateClient"
      produces:
      - "application/octet-stream"
      parameters:
      - name: "language"
        in: "path"
        description: "The target language for the client library"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Configuration for building the client library"
        required: true
        schema:
          $ref: "#/definitions/GeneratorInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
            format: "byte"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
  /gen/servers:
    get:
      tags:
      - "servers"
      summary: "Gets languages supported by the server generator"
      operationId: "serverOptions"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
  /gen/servers/{framework}:
    get:
      tags:
      - "servers"
      summary: "Returns options for a server framework"
      operationId: "getServerOptions"
      produces:
      - "application/json"
      parameters:
      - name: "framework"
        in: "path"
        description: "The target language for the server framework"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              $ref: "#/definitions/CliOption"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
    post:
      tags:
      - "servers"
      summary: "Generates a server library"
      description: "Accepts a `GeneratorInput` options map for spec location and generation\
        \ options.\n"
      operationId: "generateServerForLanguage"
      produces:
      - "application/octet-stream"
      parameters:
      - name: "framework"
        in: "path"
        description: "framework"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "parameters"
        required: true
        schema:
          $ref: "#/definitions/GeneratorInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
            format: "byte"
      x-swagger-router-controller: "io.swagger.generator.resource.SwaggerResource"
definitions:
  CliOption:
    type: "object"
    properties:
      optionName:
        type: "string"
      description:
        type: "string"
      type:
        type: "string"
        description: "Data type is based on the types supported by the JSON-Schema"
      enum:
        type: "object"
        additionalProperties:
          type: "string"
      default:
        type: "string"
  AuthorizationValue:
    type: "object"
    properties:
      value:
        type: "string"
      type:
        type: "string"
      keyName:
        type: "string"
  ResponseCode:
    type: "object"
    properties:
      code:
        type: "string"
        example: "d40029be-eda6-4d62-b1ef-d05e2e91a72a"
        description: "File download code"
      link:
        type: "string"
        example: "http://generator.swagger.io:80/api/gen/download/d40029be-eda6-4d62-b1ef-d05e2e91a72a"
        description: "URL for fetching the generated client"
  GeneratorInput:
    type: "object"
    properties:
      spec:
        type: "object"
        properties: {}
      options:
        type: "object"
        additionalProperties:
          type: "string"
      swaggerUrl:
        type: "string"
        example: "http://petstore.swagger.io/v2/swagger.json"
      authorizationValue:
        $ref: "#/definitions/AuthorizationValue"
      securityDefinition:
        $ref: "#/definitions/SecuritySchemeDefinition"
  SecuritySchemeDefinition:
    type: "object"
    properties:
      type:
        type: "string"
      description:
        type: "string"
